CREATE TABLE DIMPRODUCT AS SELECT * FROM PF1788.DIMPRODUCT;
CREATE TABLE DIMSTORE AS SELECT * FROM PF1788.DIMSTORE;
CREATE TABLE DIMTIME AS SELECT * FROM PF1788.DIMTIME;
CREATE TABLE DIMCUSTOMER AS SELECT * FROM PF1788.DIMCUSTOMER;
CREATE TABLE FACTSALES AS SELECT * FROM PF1788.FACTSALES;

select * from DIMSTORE